package com.chatting.ui.utils

import com.chatting.ui.model.Country

object CountryList {
    val countries: List<Country> by lazy {
        createCountryList()
    }

    private fun createCountryList(): List<Country> {
        return listOf(
            Country("🇦🇫", "Afeganistão", "93"),
            Country("🇦🇱", "Albânia", "355"),
            Country("🇩🇪", "Alemanha", "49"),
            Country("🇦🇩", "Andorra", "376"),
            Country("🇦🇴", "Angola", "244"),
            Country("🇦🇮", "Anguilla", "1-264"),
            Country("🇦🇶", "Antártida", "672"),
            Country("🇦🇬", "Antígua e Barbuda", "1-268"),
            Country("🇸🇦", "Arábia Saudita", "966"),
            Country("🇩🇿", "Argélia", "213"),
            Country("🇦🇷", "Argentina", "54"),
            Country("🇦🇲", "Armênia", "374"),
            Country("🇦🇼", "Aruba", "297"),
            Country("🇦🇺", "Austrália", "61"),
            Country("🇦🇹", "Áustria", "43"),
            Country("🇦🇿", "Azerbaijão", "994"),
            Country("🇧🇸", "Bahamas", "1-242"),
            Country("🇧🇭", "Bahrein", "973"),
            Country("🇧🇩", "Bangladesh", "880"),
            Country("🇧🇧", "Barbados", "1-246"),
            Country("🇧🇾", "Belarus", "375"),
            Country("🇧🇪", "Bélgica", "32"),
            Country("🇧🇿", "Belize", "501"),
            Country("🇧🇯", "Benin", "229"),
            Country("🇧🇲", "Bermudas", "1-441"),
            Country("🇧🇴", "Bolívia", "591"),
            Country("🇧🇦", "Bósnia e Herzegovina", "387"),
            Country("🇧🇼", "Botsuana", "267"),
            Country("🇧🇷", "Brasil", "55"),
            Country("🇧🇳", "Brunei", "673"),
            Country("🇧🇬", "Bulgária", "359"),
            Country("🇧🇫", "Burkina Faso", "226"),
            Country("🇧🇮", "Burundi", "257"),
            Country("🇧🇹", "Butão", "975"),
            Country("🇨🇻", "Cabo Verde", "238"),
            Country("🇰🇭", "Camboja", "855"),
            Country("🇨🇲", "Camarões", "237"),
            Country("🇨🇦", "Canadá", "1"),
            Country("🇶🇦", "Catar", "974"),
            Country("🇰🇿", "Cazaquistão", "7"),
            Country("🇹🇩", "Chade", "235"),
            Country("🇨🇱", "Chile", "56"),
            Country("🇨🇳", "China", "86"),
            Country("🇨🇾", "Chipre", "357"),
            Country("🇨🇴", "Colômbia", "57"),
            Country("🇰🇲", "Comores", "269"),
            Country("🇨🇬", "Congo", "242"),
            Country("🇨🇩", "Congo (RDC)", "243"),
            Country("🇰🇷", "Coreia do Sul", "82"),
            Country("🇨🇮", "Costa do Marfim", "225"),
            Country("🇨🇷", "Costa Rica", "506"),
            Country("🇭🇷", "Croácia", "385"),
            Country("🇨🇺", "Cuba", "53"),
            Country("🇩🇰", "Dinamarca", "45"),
            Country("🇩🇯", "Djibouti", "253"),
            Country("🇩🇲", "Dominica", "1-767"),
            Country("🇪🇬", "Egito", "20"),
            Country("🇸🇻", "El Salvador", "503"),
            Country("🇦🇪", "Emirados Árabes Unidos", "971"),
            Country("🇪🇨", "Equador", "593"),
            Country("🇪🇷", "Eritreia", "291"),
            Country("🇸🇰", "Eslováquia", "421"),
            Country("🇸🇮", "Eslovênia", "386"),
            Country("🇪🇸", "Espanha", "34"),
            Country("🇺🇸", "Estados Unidos", "1"),
            Country("🇪🇪", "Estônia", "372"),
            Country("🇪🇹", "Etiópia", "251"),
            Country("🇫🇯", "Fiji", "679"),
            Country("🇵🇭", "Filipinas", "63"),
            Country("🇫🇮", "Finlândia", "358"),
            Country("🇫🇷", "França", "33"),
            Country("🇬🇦", "Gabão", "241"),
            Country("🇬🇲", "Gâmbia", "220"),
            Country("🇬🇭", "Gana", "233"),
            Country("🇬🇪", "Geórgia", "995"),
            Country("🇬🇮", "Gibraltar", "350"),
            Country("🇬🇷", "Grécia", "30"),
            Country("🇬🇩", "Granada", "1-473"),
            Country("🇬🇱", "Groenlândia", "299"),
            Country("🇬🇵", "Guadalupe", "590"),
            Country("🇬🇺", "Guam", "1-671"),
            Country("🇬🇹", "Guatemala", "502"),
            Country("🇬🇬", "Guernsey", "44-1481"),
            Country("🇬🇼", "Guiné-Bissau", "245"),
            Country("🇬🇳", "Guiné", "224"),
            Country("🇬🇾", "Guiana", "592"),
            Country("🇭🇹", "Haiti", "509"),
            Country("🇭🇳", "Honduras", "504"),
            Country("🇭🇰", "Hong Kong", "852"),
            Country("🇭🇺", "Hungria", "36"),
            Country("🇾🇪", "Iêmen", "967"),
            Country("🇮🇲", "Ilha de Man", "44-1624"),
            Country("🇨🇽", "Ilha Christmas", "61"),
            Country("🇮🇨", "Ilhas Canárias", "34"),
            Country("🇰🇾", "Ilhas Cayman", "1-345"),
            Country("🇨🇨", "Ilhas Cocos (Keeling)", "61"),
            Country("🇨🇰", "Ilhas Cook", "682"),
            Country("🇫🇰", "Ilhas Falkland (Malvinas)", "500"),
            Country("🇫🇴", "Ilhas Faroe", "298"),
            Country("🇬🇸", "Ilhas Geórgia do Sul e Sandwich do Sul", "500"),
            Country("🇭🇲", "Ilhas Heard e McDonald", "672"),
            Country("🇲🇵", "Ilhas Marianas do Norte", "1-670"),
            Country("🇲🇭", "Ilhas Marshall", "692"),
            Country("🇵🇳", "Ilhas Pitcairn", "64"),
            Country("🇸🇧", "Ilhas Salomão", "677"),
            Country("🇹🇨", "Ilhas Turks e Caicos", "1-649"),
            Country("🇻🇬", "Ilhas Virgens Britânicas", "1-284"),
            Country("🇻🇮", "Ilhas Virgens Americanas", "1-340"),
            Country("🇮🇳", "Índia", "91"),
            Country("🇮🇩", "Indonésia", "62"),
            Country("🇮🇷", "Irã", "98"),
            Country("🇮🇶", "Iraque", "964"),
            Country("🇮🇪", "Irlanda", "353"),
            Country("🇮🇸", "Islândia", "354"),
            Country("🇮🇱", "Israel", "972"),
            Country("🇮🇹", "Itália", "39"),
            Country("🇯🇲", "Jamaica", "1-876"),
            Country("🇯🇵", "Japão", "81"),
            Country("🇯🇪", "Jersey", "44-1534"),
            Country("🇯🇴", "Jordânia", "962"),
            Country("🇰🇪", "Quênia", "254"),
            Country("🇰🇬", "Quirguistão", "996"),
            Country("🇰🇮", "Kiribati", "686"),
            Country("🇽🇰", "Kosovo", "383"),
            Country("🇰🇼", "Kuwait", "965"),
            Country("🇱🇦", "Laos", "856"),
            Country("🇱🇸", "Lesoto", "266"),
            Country("🇱🇻", "Letônia", "371"),
            Country("🇱🇧", "Líbano", "961"),
            Country("🇱🇷", "Libéria", "231"),
            Country("🇱🇾", "Líbia", "218"),
            Country("🇱🇮", "Liechtenstein", "423"),
            Country("🇱🇹", "Lituânia", "370"),
            Country("🇱🇺", "Luxemburgo", "352"),
            Country("🇲🇴", "Macau", "853"),
            Country("🇲🇰", "Macedônia do Norte", "389"),
            Country("🇲🇬", "Madagascar", "261"),
            Country("🇲🇾", "Malásia", "60"),
            Country("🇲🇼", "Malawi", "265"),
            Country("🇲🇻", "Maldivas", "960"),
            Country("🇲🇱", "Mali", "223"),
            Country("🇲🇹", "Malta", "356"),
            Country("🇲🇦", "Marrocos", "212"),
            Country("🇲🇶", "Martinica", "596"),
            Country("🇲🇺", "Maurício", "230"),
            Country("🇲🇷", "Mauritânia", "222"),
            Country("🇲🇽", "México", "52"),
            Country("🇲🇩", "Moldávia", "373"),
            Country("🇲🇨", "Mônaco", "377"),
            Country("🇲🇳", "Mongólia", "976"),
            Country("🇲🇪", "Montenegro", "382"),
            Country("🇲🇸", "Montserrat", "1-664"),
            Country("🇲🇿", "Moçambique", "258"),
            Country("🇲🇲", "Mianmar (Birmânia)", "95"),
            Country("🇳🇦", "Namíbia", "264"),
            Country("🇳🇷", "Nauru", "674"),
            Country("🇳🇵", "Nepal", "977"),
            Country("🇳🇮", "Nicarágua", "505"),
            Country("🇳🇪", "Níger", "227"),
            Country("🇳🇬", "Nigéria", "234"),
            Country("🇳🇴", "Noruega", "47"),
            Country("🇳🇿", "Nova Zelândia", "64"),
            Country("🇴🇲", "Omã", "968"),
            Country("🇳🇱", "Países Baixos", "31"),
            Country("🇵🇰", "Paquistão", "92"),
            Country("🇵🇼", "Palau", "680"),
            Country("🇵🇸", "Palestina", "970"),
            Country("🇵🇦", "Panamá", "507"),
            Country("🇵🇬", "Papua-Nova Guiné", "675"),
            Country("🇵🇾", "Paraguai", "595"),
            Country("🇵🇪", "Peru", "51"),
            Country("🇵🇫", "Polinésia Francesa", "689"),
            Country("🇵🇱", "Polônia", "48"),
            Country("🇵🇹", "Portugal", "351"),
            Country("🇵🇷", "Porto Rico", "1-787"),
            Country("🇨🇫", "República Centro-Africana", "236"),
            Country("🇨🇿", "República Tcheca", "420"),
            Country("🇩🇴", "República Dominicana", "1-809"),
            Country("🇷🇴", "Romênia", "40"),
            Country("🇷🇼", "Ruanda", "250"),
            Country("🇷🇺", "Rússia", "7"),
            Country("🇸🇭", "Santa Helena", "290"),
            Country("🇱🇨", "Santa Lúcia", "1-758"),
            Country("🇸🇲", "San Marino", "378"),
            Country("🇸🇹", "São Tomé e Príncipe", "239"),
            Country("🇸🇳", "Senegal", "221"),
            Country("🇸🇱", "Serra Leoa", "232"),
            Country("🇷🇸", "Sérvia", "381"),
            Country("🇸🇨", "Seicheles", "248"),
            Country("🇸🇬", "Singapura", "65"),
            Country("🇸🇾", "Síria", "963"),
            Country("🇸🇴", "Somália", "252"),
            Country("🇱🇰", "Sri Lanka", "94"),
            Country("🇸🇿", "Suazilândia", "268"),
            Country("🇸🇪", "Suécia", "46"),
            Country("🇨🇭", "Suíça", "41"),
            Country("🇸🇩", "Sudão", "249"),
            Country("🇸🇸", "Sudão do Sul", "211"),
            Country("🇸🇷", "Suriname", "597"),
            Country("🇹🇭", "Tailândia", "66"),
            Country("🇹🇼", "Taiwan", "886"),
            Country("🇹🇿", "Tanzânia", "255"),
            Country("🇹🇯", "Tajiquistão", "992"),
            Country("🇹🇱", "Timor-Leste", "670"),
            Country("🇹🇬", "Togo", "228"),
            Country("🇹🇴", "Tonga", "676"),
            Country("🇹🇹", "Trinidad e Tobago", "1-868"),
            Country("🇹🇳", "Tunísia", "216"),
            Country("🇹🇲", "Turcomenistão", "993"),
            Country("🇹🇷", "Turquia", "90"),
            Country("🇹🇻", "Tuvalu", "688"),
            Country("🇺🇬", "Uganda", "256"),
            Country("🇺🇦", "Ucrânia", "380"),
            Country("🇺🇾", "Uruguai", "598"),
            Country("🇺🇿", "Uzbequistão", "998"),
            Country("🇻🇺", "Vanuatu", "678"),
            Country("🇻🇦", "Vaticano", "379"),
            Country("🇻🇪", "Venezuela", "58"),
            Country("🇻🇳", "Vietnã", "84"),
            Country("🇿🇲", "Zâmbia", "260"),
            Country("🇿🇼", "Zimbábue", "263"),
            Country("🇿🇦", "África do Sul", "27")
        )
    }
}


